services:
  workspace:
    build:
      context: ./docker/workspace
      args:
        LOCALE: ${LOCALE-C}
    environment:
      TZ: ${TIME_ZONE-UTC}
    tty: true
    volumes:
      - ../:/var/www
    working_dir: /var/www

  nginx:
    build: ./docker/nginx
    ports:
      - ${IP_ADDRESS_SETTING}80:80
      - ${IP_ADDRESS_SETTING}443:443
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ../:/var/www
    environment:
      TZ: ${TIME_ZONE-UTC}
    networks:
      default:
        aliases:
          - minio.${DOMAIN-php-develop.test}

  php:
    image: ghcr.io/horatjp/php-fpm:8.2
    volumes:
      - ../:/var/www
    working_dir: /var/www

  mysql:
    image: mysql:8.0
    ports:
      - ${IP_ADDRESS_SETTING}3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-db_password}
      MYSQL_USER: ${DB_USERNAME-db_user}
      MYSQL_PASSWORD: ${DB_PASSWORD-db_password}
      MYSQL_DATABASE: ${DB_DATABASE-db_name}
      TZ: ${TIME_ZONE-UTC}

  postgres:
    image: postgres:16
    ports:
      - ${IP_ADDRESS_SETTING}5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME-db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD-db_password}
      POSTGRES_DB: ${DB_DATABASE-db_name}
      TZ: ${TIME_ZONE-UTC}

  redis:
    image: redis:7.4
    ports:
      - ${IP_ADDRESS_SETTING}6379:6379
    volumes:
      - redis:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - ${IP_ADDRESS_SETTING}5540:5540

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - ${IP_ADDRESS_SETTING}1025:1025
      - ${IP_ADDRESS_SETTING}8025:8025

  minio:
    image: minio/minio:latest
    ports:
      - ${IP_ADDRESS_SETTING}9001:9001
      - ${IP_ADDRESS_SETTING}8900:8900
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD-minio_password}
    volumes:
      - minio:/data/minio
    command: 'minio server /data/minio --address :9001 --console-address :8900'

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "sleep 15;/usr/bin/mc config host add local http://minio:9001 ${MINIO_USERNAME-minio} ${MINIO_PASSWORD-minio_password}; /usr/bin/mc mb -p local/${MINIO_BUCKET-default}; /usr/bin/mc anonymous set download local/${MINIO_BUCKET-default};"

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
  minio:
    driver: local
